### PR TITLE
Adding m1() function in the existing Class A and committing this changes

### PR DESCRIPTION
**Pull request by raghu-kpr23**
Hi TL,
I have implemented m1() functionality as per requirement in the existing Class A. Please review and approve it.

Thanks,
Raghuvir

### CODE REVIEW

**Comment by raghu-pr20** [comment]
Hi SE,
The code looks good... Please change the method name m1 to m2 as per SRS doc.

Thanks,
Prasad

**Comment by raghu-kpr23** [comment]
Hi TL,
I have change the method name as per SRS. Please approve.

Thanks,
Raghu

**Comment by raghu-pr20** [comment]
Hi SE,
The Code looks good. Please merge this branch to Master.

Thanks,
TL

**Comment by raghu-pr20** [comment]
Done

**Pull request merged**
